include:
  - template: Security/SAST.gitlab-ci.yml

stages:
  - test
  - release

pypi_upload:
  stage: release
  image: python:latest
  script:
    - pip install twine
    - python setup.py sdist bdist_wheel
    - python -m twine upload dist/*
  only:
    - tags
